#!/bin/sh -efu

# Install a filter into a database.

for n in "$@"; do

  name=${n%:*}
  flt_num=${n##*:}

  test -f $n

  flt_text=$(grep -v "^\#" $n)

  if [ "$name" = press_1K -o\
       "$name" = press_cell_panel -o\
       "$name" = press_cond -o\
       "$name" = press_misc -o\
       "$name" = press_still -o\
       "$name" = press_traps ]; then
    echo "$n -> db_rpi"
    device_c ask db_rpi set_filter "$name" "$flt_num" "$flt_text"
  fi

  for db_dev in db db_xyz; do
    echo "$n -> $db_dev"
    device_c ask $db_dev set_filter "$name" "$flt_num" "$flt_text"
  done

done

